Description: creating a ec2 Instance
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: 
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: '0' 
          SubnetId: !ImportValue MySubnetA-Id
          GroupSet:
            - !ImportValue SecurityGroupId-HTTP
      UserData: 
        Fn::Base64: !Sub |
        #!/bin/bash
